language: ruby
rvm:
- 2.1
before_install:
- travis_retry gem install html-proofer
- travis_retry gem install jekyll
script: jekyll build && htmlproof ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true