# Site settings
title:       Create.net Developers Portal
email:
author:      Create.net
description: "The Create.net developer portal."
baseurl:     ""
url:         "https://developers.create.net/"

# Google analytics
google_analytics: UA-58388268-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username: createdotnet
stackoverflow_id:
twitter_username: createdev
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown

permalink:    pretty
#paginate:     3
sass:
  compressed: true

# Travis CI - http://jekyllrb.com/docs/continuous-integration/
exclude: [vendor]
